--- #YAML:1.0
name:               Net-Jabber-Bot
version:            2.1.0
abstract:           Automated Bot creation with safeties
author:
    - Todd E Rinaldo <perl-net-jabber-bot@googlegroups.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Log::Log4perl:        0
    Moose:                0
    Moose::Util::TypeConstraints:  0
    Net::Jabber:          2
    Test::More:           0
    Test::NoWarnings:     0
    Time::HiRes:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
